name: CI/CD for Docker Image Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.AWS_REGION }}.dkr.ecr.amazonaws.com/temporal-worker:${{ env.TAG_NAME }}
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/aws-login@v1
      with:
        region: ${{ env.AWS_REGION }}

    - name: Push Docker Image to Amazon ECR
      uses: aws-actions/amazon-ecr-push-action@v1
      with:
        region: ${{ env.AWS_REGION }}
        registry-url: ${{ env.AWS_REGION }}.dkr.ecr.amazonaws.com
        image-name: temporal-worker
        tags: ${{ env.TAG_NAME }}
      env:
        AWS_REGISTRY_AUTH_TOKEN: ${{ steps.login-ecr.outputs.registry-auth }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/aws-login@v1
      with:
        region: ${{ env.AWS_REGION }}

    - name: Deploy to Kubernetes
      uses: azure/k8s-apply@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        config: deployment.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        AWS_REGISTRY_AUTH_TOKEN: ${{ steps.login-ecr.outputs.registry-auth }}
